// Historical "things to know" — encyclopedic background per night + the route itself.
// Sourced from Wikipedia + reputable references via research. Keyed by place.
const history = {
  route: {
    title: 'The Alta Via 2 — the "Way of Legends"',
    paragraphs: [
      `The Alta Via 2 delle Dolomiti is a long-distance high-mountain traverse of roughly 160–185 km that crosses the Dolomites from north to south, beginning at Bressanone (Brixen) in South Tyrol — conventionally above the city on the Plose massif — and ending at Feltre in the Veneto, typically divided into about 13 stages with on the order of 11,000–12,000 m of cumulative ascent. It is one of the network of numbered "Alte Vie" (High Routes) conceived and waymarked through the Dolomites in the 1960s as a collaboration between the Club Alpino Italiano (CAI) and regional tourism boards, who linked pre-existing CAI mountain huts, shepherds' tracks, mountaineering approaches and WWI military paths into continuous numbered itineraries. The full integral traverse was pioneered in July 1969 by Ivano Tisot and Louis Pillon of Feltre, who walked the line south to north.`,
      `Its nickname, the "Way of Legends" (Via delle Leggende), comes from the chain of Ladin sagas attached to the massifs it threads — above all the legend of King Laurin (Re Laurino) and his enchanted rose garden, which gives the Rosengarten/Catinaccio group its name. Laurin, the dwarf-king of a crystal palace, tends a garden of roses; after being betrayed by his swaying roses he curses the garden so no human eye shall see it by day or night — but, forgetting the dusk, he leaves it free to glow at twilight. The tale is the folk explanation of the enrosadira, the alpenglow by which the pale dolomite walls flush rose and violet at sunrise and sunset.`,
      `The Alta Via 2 is the harder, higher and more committing of the two flagship routes. Where the Alta Via 1 is largely a walking traverse on good paths, AV2 climbs higher, spends more time in austere rock-and-scree terrain, and includes several genuinely exposed attrezzato (cable-equipped) and via ferrata sections where iron rungs and fixed steel cables protect passages that would otherwise demand technical climbing — so a via-ferrata kit (harness, lanyard, helmet) is standard equipment. Signature difficulties include the cable-protected crossings of the Puez-Odle and the bare limestone wilderness of the Altopiano delle Pale di San Martino.`,
      `The route also traces, in places, the front line of the First World War's "White War" (Guerra Bianca), fought from 1915 to 1917, when the high Dolomites became a fortified front where cold, avalanche and rockfall killed more men than gunfire. The corridor passes through this militarised landscape — most notably around the Marmolada, where the Austro-Hungarian "Città di Ghiaccio" (Ice City) was a network of galleries carved into the glacier. Many of the ledges and tunnels the route now uses were originally wartime supply lines, and open-air relics survive along the way.`,
      `Logistically the route depends entirely on the CAI rifugi system, the staffed Alpine huts that make tent-free traversing possible. Many were founded in the late 19th and early 20th centuries by the CAI and its sections — including the SAT in Trentino — to support the first wave of Dolomite mountaineering. The entire region the AV2 crosses was inscribed on the UNESCO World Heritage List as "The Dolomites" on 26 June 2009, a serial natural property of nine mountain systems — among them Puez-Odle, Marmolada, Pale di San Martino and the Dolomiti Bellunesi — listed for exceptional natural beauty and globally outstanding geology.`,
    ],
  },
  venice: {
    title: "Venice — La Serenissima, the Lagoon Republic",
    paragraphs: [
      `Venice (Venezia) is built on an archipelago of some 118 small islands in a shallow tidal lagoon at the head of the Adriatic, stitched together by hundreds of bridges. Settlement was driven by refuge: mainland Veneti fleeing Germanic and Hunnic invasions during the collapse of the Western Roman Empire retreated to the defensible marshes from the 5th to 7th centuries. By tradition the line of doges — the elected heads of state who would rule for over 1,100 years — began in 697 under nominal Byzantine authority.`,
      `In 828 Venetian merchants famously smuggled the relics of St Mark the Evangelist out of Alexandria, and the saint's winged lion became the emblem of the state. Over the medieval centuries Venice became the dominant maritime republic of the Mediterranean, its wealth built on the spice and luxury trade with Byzantium and the Levant; its merchant Marco Polo (1254–1324) journeyed to the court of Kublai Khan. The republic's title, the "Most Serene Republic" (La Serenissima), reflected an oligarchic constitution engineered to prevent any one family seizing power.`,
      `The turning point came with the Fourth Crusade: in 1204 the blind Doge Enrico Dandolo diverted it to sack Constantinople, carving out a commercial empire across Greece, Crete and the Aegean (the bronze horses of St Mark's were among the plunder). At its height in the 15th–16th centuries Venice controlled a Stato da Mar of overseas colonies; overreach on the mainland provoked the League of Cambrai (1508) and a crushing defeat at Agnadello in 1509. The thousand-year republic ended in May 1797, when Napoleon forced the last doge to abdicate.`,
      `The historic city is divided into six sestieri. Cannaregio, the populous northern district, holds the Venetian Ghetto — established by Senate decree in 1516, the first compulsory Jewish quarter in the world (geto, from a former foundry, is the likely root of the word "ghetto"). Dorsoduro, the high-ground sestiere along the Giudecca Canal, concentrates Venice's great art institutions: the Gallerie dell'Accademia and the domed votive Basilica di Santa Maria della Salute, begun in 1631 in thanksgiving for the end of a plague. Venice and its lagoon have been a UNESCO World Heritage Site since 1987 — and the classic gateway by rail into the Dolomites.`,
    ],
  },
  bressanone: {
    title: "Bressanone / Brixen — South Tyrol's oldest town",
    paragraphs: [
      `Bressanone (German Brixen, Ladin Persenon) lies at the confluence of the Eisack (Isarco) and Rienz rivers and is the oldest town in the historic Tyrol. The name first appears in a deed of 901, when King Louis the Child granted the estate of "Prihsna" to the Bishop of Säben; the bishopric moved down to Brixen around 990, and the settlement grew into a walled town, with the cathedral, the bishop's residence and town walls completed by roughly 1150.`,
      `For nearly eight centuries Brixen's significance lay in its prince-bishops. In 1027 Emperor Conrad II granted them temporal sovereignty, creating an ecclesiastical principality of the Holy Roman Empire near the Brenner Pass — a bridge between the German and Italian worlds. Its most celebrated prince-bishop was Nicholas of Cusa (Cusanus), the great Renaissance philosopher and reformer, who held the see from 1450 and was imprisoned in 1460 by Duke Sigismund of Austria after a bitter conflict over diocesan revenues.`,
      `Two monuments define the cathedral square: the Baroque Duomo, rebuilt in the mid-18th century over a 10th-century church, with a Romanesque cloister famous for richly painted 14th–15th-century frescoes; and the Hofburg, the prince-bishops' 13th-century palace, expanded into a grand Renaissance and Baroque residence. Just north of town, the Augustinian abbey of Neustift (Novacella), founded in 1142, is one of the most important monastic complexes in the Alps, with a celebrated library and ancient winery.`,
      `Brixen's independence ended with secularization in 1803, when it was annexed to Austria; it remained Austrian through the 19th century. After the First World War, by the Treaty of Saint-Germain (1919), Brixen and the rest of overwhelmingly German- and Ladin-speaking South Tyrol were transferred to Italy and the town acquired its Italian name. Today it sits within the autonomous province of Bolzano. For trekkers it is the traditional start of the Alta Via 2 — the cultural and logistical threshold where hikers ride the Plose gondola to gain the high ground.`,
    ],
  },
  halsl: {
    title: "The Plose, Peitlerkofel & Würzjoch — gateway to the AV2",
    paragraphs: [
      `Above Brixen rises the Plose, a broad grassy massif (its summit, the Gabler, reaches about 2,562 m) served by a cable car from St. Andrä. The Plose is the practical starting point of the Alta Via 2: from the top of the gondola, walkers head south and east across alpine pasture toward the first great rock peaks. This high country between the Plose, the Würzjoch and the Peitlerkofel marks the transition from the soft grasslands of the South Tyrolean foreland into the abrupt pale-limestone towers that define the range proper.`,
      `The Peitlerkofel (Ladin Sass de Pütia, 2,875 m) is a strikingly isolated double-summit massif, generally regarded as the northernmost true peak of the Dolomites. It stands on the boundary between Val Badia and Val di Funes (Villnöss), rising in dramatic solitude above meadows. Reaching the Peitlerscharte (Forcella di Putia), the saddle at its foot, is the point at which AV2 walkers enter the Puez-Odle Nature Park; from the saddle a via ferrata gives an optional ascent of the summit.`,
      `The Würzjoch (Passo delle Erbe, about 2,004 m) is the road pass that crosses this country, linking Brixen with the Ladin Val Badia and separating the Peitlerkofel from the Lüsen mountains to the north. The pass and its pastures are heavily Ladin in character and form the start of the classic Peitlerkofel circuit. For AV2 trekkers it is a key waypoint between the Plose and the Puez-Odle high plateau.`,
      `The hub hut for this section is the Schlüterhütte (Rifugio Genova), built in 1898 with funds donated by the German industrialist Franz Schlüter, near the Forcella Poma between the Peitlerkofel and the Odle (Geisler) group. After the First World War and the transfer of South Tyrol to Italy, the hut — like many German-Austrian Alpine Club refuges — passed to the CAI, acquiring its Italian name Rifugio Genova. It is the standard waypoint where the route enters the heart of the Puez-Odle park.`,
    ],
  },
  puez: {
    title: "Puez-Odle / Geisler — an open-air geology textbook",
    paragraphs: [
      `The Puez-Odle Nature Park (German Naturpark Puez-Geisler, Ladin Parch Naturel Pöz-Odles) protects roughly 10,722 hectares of Dolomite landscape and was established in 1978. Bounded by the Würzjoch to the north and the Passo Gardena to the south, it unites three groups — the jagged Geisler/Odle spires, the lonely Peitlerkofel, and the broad high plateau of the Puez group — making it the geological and scenic core through which the Alta Via 2 passes after leaving Brixen.`,
      `The park is renowned as an "open-air geology textbook." Within its bounds one can trace the entire stratigraphic sequence of the Dolomites, from the Permian through the Cretaceous — roughly 200–250 million years of Earth history — exceptionally well preserved and little deformed. The rock layers record the rise and drowning of ancient tropical reefs and carbonate atolls in the warm Tethys sea, the very process that gives the Dolomites their platforms and towers.`,
      `In 2009 the Dolomites were inscribed on the UNESCO World Heritage List, and Puez-Odle is one of the nine systems that make up that serial property. The inscription rests on its exceptional natural beauty — the pale walls and pinnacles that glow at sunset — and its outstanding geological value as a classic locality for mountain-building in dolomitic limestone, shaped by erosion, tectonics and glaciation.`,
      `Puez-Odle lies at the heart of Ladinia, homeland of the Ladin people, a Rhaeto-Romance minority whose language descends from the Vulgar Latin of Roman Raetia. In the surrounding Val Gardena (Gherdëina) and Val Badia (Badiot), Ladin remains a living daily language and the third official language of South Tyrol. Place-names within the park — Sass de Pütia, Odles, Pöz — preserve this heritage.`,
      `The principal refuge is the Rifugio Puez (Puezhütte), at about 2,475 m on the high tableland. First built in 1889 by the German-Austrian Alpine Club, it passed after WWI to the Bolzano CAI; in 1940 it came under the Val Badia guide Pietro Costa, whose family still runs it, and the present building opened in 1982 in the presence of Italian President Sandro Pertini. Standing directly on the AV2, it is the natural second base for trekkers crossing the park.`,
    ],
  },
  pisciadu: {
    title: "The Sella group, Piz Boè & the Pisciadù",
    paragraphs: [
      `The Sella is a roughly circular, plateau-shaped massif at the geographic heart of the Dolomites, ringed by four high passes — Gardena, Sella, Pordoi and Campolongo. Its summit, Piz Boè, rises to 3,152 m. Geologically it is a textbook of Dolomite architecture: a near-flat summit plateau of pale Triassic dolostone ringed by sheer walls that follow fault planes — rock that began as a tropical reef and lagoon in the Tethys Ocean roughly 250 million years ago, later uplifted during the Alpine orogeny. The Sella was inscribed as part of the Dolomites UNESCO site in 2009.`,
      `The valleys encircling the Sella — Gardena, Badia, Fassa, Livinallongo and Ampezzo — form Ladinia; roughly 30,000 people still speak Ladin across these valleys, and place-names reflect it (the Pisciadù hut is Ütia de Pisciadú in Ladin). The Pisciadù itself is a high glacial cirque holding a small lake beneath the towers of the Sella's northern rim — the classic contrast between the gentle interior plateau and the abrupt encircling walls.`,
      `The Rifugio Franco Cavazza al Pisciadù sits at 2,585 m on a shelf above the lake. It was built in 1903 by the Bamberg section of the German and Austrian Alpine Club as the Bamberger Hütte, renovated in 1924, and in 1942 bought by the Bologna CAI, which renamed it for Count Franco Cavazza (1915–1941), a Bologna CAI member and Alpine lieutenant killed at Monte Golico in the Greek campaign. It remains a CAI Bologna refuge and a key waypoint on the AV2.`,
      `The most celebrated approach is the via ferrata Brigata Tridentina, one of the most frequented protected routes in the Dolomites — steel cables, iron rungs and a dramatic suspension bridge at roughly 2,430 m before the plateau and the Cavazza hut. It is named for the Army's Alpine Brigade "Tridentina" and was equipped in 1968, placing it among the post-war generation of via ferrate.`,
      `Though the 1915–1917 front ran chiefly along the western and southern edges of the Dolomites, the wider Sella lies within the theatre of the "White War," the high-altitude struggle where avalanche, frostbite and exposure killed as many men as enemy fire. The dense network of huts, mule tracks and engineered paths that makes the Sella so accessible today owes much to that militarised infrastructure and the Alpine clubs that built it.`,
    ],
  },
  fedaia: {
    title: "The Marmolada, Passo Fedaia & the City of Ice",
    paragraphs: [
      `The Marmolada is the highest massif of the Dolomites, the "Queen of the Dolomites." Its summit, Punta Penia, reaches 3,343 m — the highest point in the range. It has a dramatic dual character: a long, sheer south face famed among rock climbers, and a gentler northern flank occupied by the only large glacier in the Dolomites. The first recorded ascent was on 28 September 1864 by the Austrian alpinist Paul Grohmann with the guides Angelo and Fulgenzio Dimai. The Marmolada was inscribed in the Dolomites UNESCO site in 2009.`,
      `The glacier has become a stark emblem of glacial retreat, losing most of its volume over the past century. On 3 July 2022 a serac collapse near Punta Rocca killed eleven people, a disaster linked to record temperatures and the destabilization of the warming ice — bringing international attention to the glacier's decline.`,
      `During the First World War the Marmolada lay directly on the front, and its glacier became the site of the Città di Ghiaccio, the "City of Ice." Between 1916 and 1917 the Austro-Hungarian engineer Leo Handl directed the excavation of a network of tunnels, dormitories, kitchens, a chapel and infirmaries dug inside the glacier itself — eventually around 12 km long, reaching 50 m below the surface. The system let troops move and resupply unseen by Italian positions; with no precedent for tunnelling through moving ice, Handl's men improvised as they went.`,
      `Lago di Fedaia is a reservoir at roughly 2,050 m at the foot of the Marmolada's northern slopes, created by a dam completed around 1955 as part of the hydroelectric development of the eastern Alps. Today it is one of the most photographed sites in the Dolomites, the glaciated peak rising directly above the water.`,
      `Above the lake stands the Rifugio Castiglioni Marmolada (about 2,057 m), whose lineage reaches back to the Marmolada Hütte built in the early 1900s by the Bamberg DuÖAV, devastated in the Great War and rebuilt in the 1930s by the Milan CAI. It is named for Ettore Castiglioni (1908–1944), the great Italian alpinist, guidebook author and antifascist partisan who helped refugees escape across the Alps and died in the mountains during the war.`,
    ],
  },
  sanpellegrino: {
    title: "Passo San Pellegrino, Fuciade & the Monzoni",
    paragraphs: [
      `Passo San Pellegrino is a high pass at 1,918 m linking Moena in the Val di Fassa with Falcade in the upper Biois valley. It is a historic crossing — the name recalls a medieval hospice dedicated to Saint Pellegrino that sheltered travellers — and today a hiking and ski-touring hub. For long-distance walkers it is a key staging point on the AV2, between the Marmolada group to the north and the Pale di San Martino to the south.`,
      `South of the pass opens the Fuciade basin, reached by an easy track and regarded as one of the most beautiful high meadows in the Dolomites — a broad green amphitheatre of pastures and larches ringed by jagged peaks. Long used as summer alpine pasture (malga), Fuciade remains a working high-mountain landscape of hay meadows and grazing, prized as a quiet counterpoint to the busier passes nearby.`,
      `The peaks framing the pass belong to a geologically remarkable corner of the Alps. The nearby Monzoni and Predazzo complexes are kilometre-scale igneous intrusions emplaced into the older carbonate platforms — a rare interruption of the otherwise sedimentary Dolomite story. The Monzoni are internationally significant as the type locality of monzonite, the rock named after them; their contact zones produced a famous suite of minerals that has drawn mineralogists since the 1800s.`,
      `Culturally the pass lies on the linguistic frontier of Ladinia. Moena, at the head of the Val di Fassa approach, is one of the historic Ladin communities of the Fassa valley, where the Fassan dialect of Ladin is still spoken. The traditions of these valleys — alpine pasturing, woodcraft, and a rich body of Ladin legend tied to specific peaks — remain woven into the landscape of Fuciade and the surrounding mountains.`,
    ],
  },
  mulaz: {
    title: "The northern Pale di San Martino & Rifugio Mulaz",
    paragraphs: [
      `The Pale di San Martino is the largest mountain group of the Dolomites, a vast massif whose interior is occupied by the Altopiano delle Pale — a high, almost lunar rock plateau of roughly 50 km² lying between about 2,500 and 2,700 m. It was once a carbonate reef and lagoon in the Tethys some 200–250 million years ago, the plateau corresponding to the former inner lagoon, later uplifted and stripped by erosion. Its principal summits include Cima della Vezzana (3,192 m) and the iconic pyramid of Cimon della Pala (3,184 m); the northern sector is crowned by Monte Mulaz (about 2,906 m).`,
      `The Pale, together with San Lucano, the Dolomiti Bellunesi and the Vette Feltrine, form one of the nine systems of the Dolomites UNESCO site inscribed in 2009. Covering more than 31,000 hectares, it is among the largest and most pristine — both bare high plateau and deep, forested valleys — a landscape famously associated with the writer Dino Buzzati.`,
      `Monte Mulaz gives its name to the Rifugio Giuseppe Volpi al Mulaz, at 2,571 m at the Passo del Mulaz at the head of the Val Focobon. The hut was promoted by CAI Venezia and completed in 1907 by the builder Emanuele Murer; the Municipality of Falcade supplied timber from its forests, and the refuge was inaugurated on 10 September 1907, with an access path opened on the Trentino side linking Passo Rolle to the new hut.`,
      `The refuge was named for Giuseppe Volpi, Count of Misurata (1877–1947), the Venetian industrialist who founded the electrical utility SADE and the Venice Film Festival — reflecting both CAI Venezia's patronage networks and the era's habit of naming huts for benefactors. Still operated by CAI Venezia, it remains one of the historic refuges of the Pale, more than a century after its founding.`,
      `Strategically placed at the junction of the Val Venegia, Passo Valles and Passo Rolle approaches, the Mulaz hut is a classic base for the northern Pale and a key stage of the Alta Via 2. As with much of the range, its surrounding paths and ridges bear the imprint of the 1915–1917 mountain war, when the Pale stood within the Dolomite front of the "White War."`,
    ],
  },
  rosetta: {
    title: "The Pale plateau & the Rifugio Rosetta",
    paragraphs: [
      `The Altopiano delle Pale di San Martino is a stark, lunar limestone plateau at roughly 2,500–2,600 m at the heart of the largest Dolomite massif. Geologically it is the eroded summit of a Triassic carbonate platform laid down 200–230 million years ago as a tropical reef, then uplifted and fractured during the Alpine orogeny. Glaciation and karst dissolution scoured it into the bare, fissured "deserto di pietra" (desert of stone) that defines it today, dotted with karren, sinkholes and the small residual Fradusta glacier.`,
      `The Pale entered the European imagination through Victorian Britain. The 1864 travelogue "The Dolomite Mountains" by Josiah Gilbert and George Cheetham Churchill popularised the range among English alpinists and effectively coined "the Dolomites" as a destination. The slender Cimon della Pala (3,184 m), "the Matterhorn of the Dolomites," was first climbed in 1870 by the Englishman Edward Whitwell with guides Christian Lauener and Santo Siorpaes. The same era saw Leslie Stephen — pioneering alpinist and father of Virginia Woolf — present "The Peaks of Primiero" to the Alpine Club in London.`,
      `San Martino di Castrozza, the village at the western foot, grew from a medieval hospice dedicated to Saint Martin, tended for centuries by monks. By the late 19th century it had become one of the earliest Dolomite climbing and tourism resorts; much of the old village was destroyed by fire during the First World War, when the front ran through these mountains, and the modern resort was rebuilt between the wars.`,
      `The Rifugio Rosetta "Giovanni Pedrotti" is the gateway hut to the plateau and one of the oldest refuges of the SAT (Società degli Alpinisti Tridentini). First built in 1889, the present structure dates from a 1952 reconstruction and carries the name of Giovanni Pedrotti, SAT president 1925–1928. At about 2,581 m on the western lip of the altopiano, it is today reached by the Rosetta cable car from San Martino and serves as a hub for the AV2 and the Palaronda circuits.`,
    ],
  },
  laritonda: {
    title: "Val Canali, Villa Welsperg & the Paneveggio park",
    paragraphs: [
      `Val Canali is a quiet, pastoral side-valley of the Primiero, often called one of the most beautiful valleys in the Alps, running beneath the eastern and southern walls of the Pale di San Martino. Where the high plateau is austere rock, Val Canali is a softer landscape of meadows, larch and spruce forest and grazing pasture overlooked by dramatic towers such as the Sass Maor and the Cima Canali — a showcase of the traditional managed landscapes the surrounding park exists to protect.`,
      `Villa Welsperg is the valley's cultural anchor. Built in 1853 as the country residence of the Counts of Welsperg, an old Tyrolean noble family long established in the Primiero, the estate is a small complex of villa, chapel and barn set in meadow and garden. After passing out of noble use it was restored and, since 1996, has served as the headquarters and principal visitor centre — the "Casa del Parco" — of the park authority.`,
      `The Parco Naturale Paneveggio–Pale di San Martino was established in 1967, among the first protected areas created by the autonomous Province of Trento, and enlarged in 1987 to roughly 20,000 hectares. It spans three worlds: the bare dolomite plateau and peaks of the Pale; the spruce forest of Paneveggio, famous as the "Foresta dei Violini" because its slow-grown resonance spruce has supplied luthiers — by tradition including Stradivari — with tonewood for centuries; and the dark volcanic ridges of the eastern Lagorai.`,
      `Culturally the Primiero and Val Canali lie at the meeting point of Italian, Tyrolean-German and Ladin influences, sharing the Ladin substrate of place-names and alpine pastoral traditions. Together with the Pale plateau above it, Val Canali belongs to the system inscribed as a UNESCO World Heritage Site in 2009, the park serving as the institution that manages and interprets this landscape for visitors.`,
    ],
  },
  cereda: {
    title: "Passo Cereda, Primiero & the Vallalta mercury mines",
    paragraphs: [
      `Passo Cereda (about 1,361 m) is the saddle that links the Primiero valley around Fiera di Primiero and Tonadico with the Agordino to the east, threading between the southern bastions of the Pale di San Martino and the Cimonega group. For walkers on the Alta Via 2 it is a key crossing and roadhead between the high dolomite country to the north and the wilder Dolomiti Bellunesi to the south. Fiera di Primiero takes its name ("fiera" = fair) from the medieval markets that grew up around its trade in metals and timber.`,
      `Primiero's history is inseparable from mining. From the late Middle Ages the valley's silver, copper, iron and lead deposits drew Tyrolean and German miners, and for much of its history the district lay under Habsburg rule as part of Tyrol. The boundary between this Austrian Primiero and the Italian/Venetian lands to the south ran through these mountains — a frontier that acquired grim significance in the First World War, when the front of the "Guerra Bianca" passed close and many valleys were militarised and evacuated.`,
      `The most remarkable mining story is the cinnabar (mercury sulphide) deposit of Vallalta, above Sagron Mis at the head of the Mis valley. Mining is documented from the 18th century, with the first concession granted in 1740. The orebody straddled the Austro-Italian frontier: it was worked from two adits a few metres apart — Vallalta on the Italian side and Terrabugio on the Austro-Hungarian side — which for political reasons were kept unconnected until the tunnels were finally joined in 1922.`,
      `Vallalta peaked in the 1860s–1870s, when it ranked among the ten most important mercury mines in Europe, employing around 200 people underground. A celebrated condensation furnace, the "Forno di Vallalta," was first fired in 1856 and entered the metallurgical literature. The mine operated, with interruptions, for more than two centuries before closing in 1963; its ruined galleries and furnaces survive as an industrial-heritage and geological site within the park's orbit.`,
    ],
  },
  boz: {
    title: "The Dolomiti Bellunesi, the Cimonega & Rifugio Boz",
    paragraphs: [
      `South of Passo Cereda the trek enters the Dolomiti Bellunesi, the wild southern Dolomites of Belluno province, protected as the Parco Nazionale Dolomiti Bellunesi, established in 1988. Unlike the resort-fringed massifs to the north, this is a largely uninhabited range of deep, forested valleys and isolated limestone groups, prized for its botanical richness — including endemic and relict plants that survived the Ice Ages on these refuge peaks — and the near-total absence of roads, lifts and villages in its interior.`,
      `The Cimonega is the dramatic northern dolomite group of the park, a compact wall of pale towers culminating in the Sass de Mura (about 2,547 m), the highest summit of this section and the second-highest in the national park. Of the same Triassic dolomite lineage as the great northern massifs, its position deep in the Bellunese means it is far less frequented, retaining a genuinely remote alpine character that the Alta Via 2 traverses in some of its most committing stages.`,
      `Rifugio Boz sits at about 1,718 m in an open hollow of alpine pasture below the Sass de Mura, the base for the network of routes through the Cimonega. The hut was opened in 1970 and is dedicated to Bruno Boz, a mountaineer and member of the CAI section of Feltre, who died in a fall near Passo Alvis; it is run today within the CAI hut system and is a key staging post for the southern Alta Via 2.`,
      `Beyond the Cimonega lies the Val di Comedon, one of the most secluded valleys of the entire Dolomites — a steep, trackless, densely wooded basin with almost no habitation, emblematic of the "wild" Dolomiti Bellunesi. Never developed for mass tourism, such valleys were historically used only for seasonal grazing and charcoal-burning, leaving them as some of the most pristine forest and karst landscapes in the Alps. Crossing this terrain is the passage through the loneliest country of the whole route.`,
    ],
  },
  feltre: {
    title: "Feltre, the Vette Feltrine, Croce d'Aune & Pedavena",
    paragraphs: [
      `Feltre, the historic terminus of the Alta Via 2, is one of the most graceful small Renaissance towns of the Veneto, set on a hill at the foot of the southern Dolomites. Its origins are Roman: known as Feltria, described by Pliny the Elder, it gained the status of municipium in 49 BC. Through the Middle Ages it passed from Lombard rule to the Da Camino and the Scaligers of Verona before being absorbed by the Republic of Venice in 1404, whose Lion of Saint Mark still presides over the upper town.`,
      `Feltre's appearance is the product of a catastrophe. In 1509–1510, during the War of the League of Cambrai, the town — loyal to Venice — was sacked and largely burned by Imperial forces. The rebuilding gave Feltre its harmonious 16th-century core: the cobbled spine of Via Mezzaterra and the Piazza Maggiore, ringed by Renaissance palaces once richly frescoed, the Palazzo della Ragione with its Palladian portico, the castle and clock-tower, and a fountain attributed to Tullio Lombardo — one of Italy's most coherent surviving Renaissance hill-towns.`,
      `Rising directly above the town are the Vette Feltrine, the southernmost rampart of the Dolomites and the botanical heart of the Dolomiti Bellunesi National Park. These limestone ridges and high cirques — reached on the AV2 via the Rifugio Dal Piaz — are renowned for an exceptional flora, including glacial-relict and endemic species, owing to their position as an unglaciated refuge at the edge of the range. They belong to the system inscribed as a UNESCO World Heritage Site in 2009.`,
      `On the mountain road above Feltre lies the Croce d'Aune pass (about 1,015 m), a site of unexpected significance. On 11 November 1927 the amateur racer Tullio Campagnolo, leading a climb in freezing conditions, could not loosen the frozen wing-nuts to flip his rear wheel and change gear, and lost the race. His reported words in dialect — roughly "something at the back has to change" — became cycling legend: the mishap led him to invent the quick-release skewer and found the Campagnolo company in 1933, the world's most celebrated maker of bicycle components.`,
      `Feltre's industrial heritage is crowned by the Birreria Pedavena, at the foot of the Croce d'Aune road. Begun by the Luciani brothers in 1896 and opened in 1897, it grew into one of the largest breweries in Italy and a defining local institution. Its monumental Liberty-era buildings, vast beer-garden and continuing production — independently revived in 2006 after a threatened closure — make Pedavena a fitting final waypoint, pairing the route's alpine grandeur with the conviviality of one of Italy's historic brewing towns.`,
    ],
  },
};

module.exports = history;
